export const Effects: {
  KILL: 'KILL';
  SPECTATE_ROLE: 'SPECTATE_ROLE';
  SELECT_PRESIDENT: 'SELECT_PRESIDENT';
  SPECTATE_CARDS: 'SPECTATE_CARDS';
} = {
  KILL: 'KILL',
  SPECTATE_ROLE: 'SPECTATE_ROLE',
  SELECT_PRESIDENT: 'SELECT_PRESIDENT',
  SPECTATE_CARDS: 'SPECTATE_CARDS',
};
